steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/PROJECT_ID/$_IMAGE_NAME:$COMMIT_SHA', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/PROJECT_ID/$_IMAGE_NAME:$COMMIT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - '$_SERVICE_NAME'
  - '--platform=managed'
  - '--image'
  - 'gcr.io/PROJECT_ID/$_IMAGE_NAME:$COMMIT_SHA'
  - '--region'
  - '$_REGION'
  - '--allow-unauthenticated'
images:
- 'gcr.io/PROJECT_ID/$_IMAGE_NAME:$COMMIT_SHA'


substitutions: 
  _IMAGE_NAME: useweb
  _REGION: us-central1
  _SERVICE_NAME: useweb
